### ISSUE TITLE
HTML chart for 2014 demograpfics of USA cycling

### ISSUE THREAD

**Issue by Restuta** [Restuta/rcn.io#1]
Create html version using D3 charts, so we can easily update it. Important requirements:
 * we should be able to update the chart easily by just modifying JSON data
 * we should be able to clone chart (in case if we want other year stats)

- [x] create Stacked area chart `Categories x Age`
 - [x] separate version for women
- [x] verify racers amount in all categories
- [ ] make sure JSON is loaded using AJAX
- [x] create separate version of stacked chart by discipline (road, mountain, cross, track)
 - [x] create data divided by discipline type from collected info
 - [x] transform road data in JSON and build the chart 
 - [x] separate road version for women
 - [x] repeat previous two tasks for mountain, cross, track
- [ ] create non-stacked chart `Categories x Age`
 - [x] create the template of line chart
 - [ ] separate version for women

**Comment by Me4ta** [comment]
<img width="1373" alt="menall" src="https://cloud.githubusercontent.com/assets/5394744/11381440/f858cd0c-92b0-11e5-9fb8-b4e2a0f79251.png">
<img width="1370" alt="mencc" src="https://cloud.githubusercontent.com/assets/5394744/11381479/2f67eab2-92b1-11e5-8854-fb70bd8c280a.png">
<img width="1369" alt="menmtb" src="https://cloud.githubusercontent.com/assets/5394744/11381482/2f6bc966-92b1-11e5-9596-c6e3c0597b75.png">
<img width="1380" alt="menroad" src="https://cloud.githubusercontent.com/assets/5394744/11381480/2f693304-92b1-11e5-8b14-9d086c8dc7b3.png">
<img width="1371" alt="mentrack" src="https://cloud.githubusercontent.com/assets/5394744/11381484/2f6ddbe8-92b1-11e5-92d4-869cb2acc9f6.png">
<img width="1368" alt="womenall" src="https://cloud.githubusercontent.com/assets/5394744/11381483/2f6c8c48-92b1-11e5-88dc-0427a5edd6b2.png">
<img width="1376" alt="womencc" src="https://cloud.githubusercontent.com/assets/5394744/11381481/2f6a3718-92b1-11e5-8e0f-b962afacdcd0.png">
<img width="1373" alt="womenmtb" src="https://cloud.githubusercontent.com/assets/5394744/11381487/2f80fbf6-92b1-11e5-812b-6636b0f4aff8.png">
<img width="1372" alt="womenroad" src="https://cloud.githubusercontent.com/assets/5394744/11381485/2f7dab40-92b1-11e5-996f-ea77b7230a59.png">
<img width="1369" alt="womentrack" src="https://cloud.githubusercontent.com/assets/5394744/11381486/2f7f1de0-92b1-11e5-8433-6bad68854db4.png">

**Comment by Me4ta** [comment]
<img width="910" alt="menroad" src="https://cloud.githubusercontent.com/assets/5394744/11381498/4578e4b4-92b1-11e5-9ada-c2c297550db7.png">

**Comment by Restuta** [comment]
@Me4ta please add simple chart labels, e.g. for last one it could be "Amount of people by Age in each Category"

**Comment by Me4ta** [comment]
@Restuta done

**Comment by Restuta** [comment]
@Me4ta I think we can close this issue
