### ISSUE TITLE
Gather team/club stats

### ISSUE THREAD

**Issue by Restuta** [Restuta/rcn.io#12]
We need the following:

- [x] total teams in CA
- [x] active teams in CA _("active" is a team with more that 0 points)_
- [x] active teams in CA by year _(to see trends, simple chart would be nice)_
- [ ] active teams in USA[1][2][3] _(https://www.usacycling.org/clubs/)_

Set [BAT point archives](http://www.ncnca.org/sites/default/files/internal/points/points-archive.html), "Team Points" sections

--
_[1] idk how to differentiate club from racing team using USA Cycling, but we can approximate. Like see how many total Clubs for CA in USA Cycling and use BAT Points Archives to see which ones are Racing Clubs. Using that we can assume similar for other states._

_[2]_ Notice that USA Cycling lists only clubs current for 2015. And in BAT archives there is no 2015 stats yet, but they are available [here](http://www.ncnca.org/sites/default/files/internal/points/Team-points15.html).

_[3]_ Also notice that BAT Points archives combine Northe CA and Nevada and those are two separate pages on USA Cycling https://www.usacycling.org/clubs/clubsearch.php?state=CN and https://www.usacycling.org/clubs/clubsearch.php?state=NV respectively

**Comment by Me4ta** [comment]
**2015. Active is > 0 points/year.**

           |USA| CN
---------|------| -------------
Active |   -   | 73 (65.77%)
Total   |   -   | 111

**Comment by Me4ta** [comment]
**2014. Active is > 0 points/year.**

           |USA| CN
---------|------| -------------
Active |   -   | 80 (65.04%)
Total   |   -   | 123

**Comment by Me4ta** [comment]
Year	Total |	Max points amount	 | > 0 |	%|	> = 20|	%
--------------|---------------------------------|------|-------|------------|-------
2015 |	111	|4910	|73	|65.77%	|66	|59.46%
2014 |	123	|5150	|80	|65.04%	|75	|60.98%
2013 |	130	|5653	|86	|66.15%	|84	|64.62%
2012 |	103	|4022	|73	|70.87%	|66	|64.08%

**Comment by Restuta** [comment]
@Me4ta is it fast for you to build a chart just for last year like that: 

![scannable document 2 on nov 10 2015 1_54_04 pm](https://cloud.githubusercontent.com/assets/377261/11076991/a3c1d486-87b2-11e5-857b-c9107764642e.png)

**Comment by Me4ta** [comment]
I think 30-40 mins, I'm not sure about the team names on the x-axis

**Comment by Restuta** [comment]
@Me4ta what do you mean "I am not sure"?

**Comment by Restuta** [comment]
@Me4ta can yo do it and post screenshot here as well?

**Comment by Me4ta** [comment]
I cannot do the "chart just for last year", since I dk how to drew the x-axis contains a team names.

**Comment by Me4ta** [comment]
<img width="978" alt="teamamount" src="https://cloud.githubusercontent.com/assets/5394744/11381525/641439d2-92b1-11e5-8b19-c8ce0eef9c26.png">

**Comment by Me4ta** [comment]
Year |	Total teams N-CA&NV	| Total clubs N-CA + NV	| % teams in clubs
--------|--------------------------|----------------------|------------------
2015 |	111	| 193 |	57.51%

**Comment by Restuta** [comment]
@Me4ta could you please update it with definition of a "club" and a "team"

**Comment by Me4ta** [comment]
Teams are members of NCNCA BAT points list. They have a team they were going to take part in some races.
Clubs are members of [USA cycling list](https://www.usacycling.org/clubs/clubsearch.php?state=CN) as clubs. Some of them have recently expired license and highlighted in red

**Comment by Me4ta** [comment]
I think we can measure active clubs in USA later, so we can close this issue. What do you think, @Restuta?

**Comment by Restuta** [comment]
sure, we need to move this to WIKI @Me4ta, simple Link to this issue would do it, don't spend time
