### ISSUE TITLE
Implement Sketched UI in our App (Main page skeleton)

### ISSUE THREAD

**Issue by Restuta** [Restuta/rcn.io#13]
We've already created UI sketches online and on paper (see #6), we need to move them as is to our web app, this  includes:

- [x] create a basic grid layout (decide will it be 12, 16 or other grid)
- [x] setup bootstrap grid
- [x] create basic calendar look with stubs for event cards showing 7 days of week + two month (8 weeks)
- [x] logo at the left and menu on the right, very basic 
- [x] plug in generated events from #20 

Just black and white or "one color" version, to reduce the friction. 

_umbrella #3_

**Comment by Restuta** [comment]
we like  this for overall look
![bedoun__2x](https://cloud.githubusercontent.com/assets/377261/12939122/d3925e50-cf70-11e5-8509-a567546df6a7.jpg)

**Comment by Me4ta** [comment]
Love this issue and those examples! :) Looking forward to see it's done.
