### ISSUE TITLE
The pop up title shouldn't be a link

### ISSUE THREAD

**Issue by Me4ta** [Restuta/rcn.io#165]
Mobile, safari, both modes, draft NCNCA

1. Open any card
2. Click on the title or on the promoter name

It rebuilds the pop up as a page, while it shouldn't. (promoter link points to nothing)

![slack for ios upload png](https://cloud.githubusercontent.com/assets/5394744/17453723/6b4520c0-5b35-11e6-8da7-f0142dcd5bdd.jpeg)

**Comment by Restuta** [comment]
fixed, in next deploy
