### ISSUE TITLE
Landing page for email collection

### ISSUE THREAD

**Issue by Restuta** [Restuta/rcn.io#26]
Before we do our first public MVP release we need to set up a very simple page that would explain RCN idea in one sentence and have a link to a blog post with longer description. 

We should smartly ask for email promising that we won't spam, that we would do just _one thing_ – notify when it's ready. 

We might also tell what is the planned release date.

##### Typeform
For email collection we can use just a simple Typeform. Pros/cons:
* :cat: simple to set up
* :imp: we can't control UI much

##### Our stack
Alternatively it might be a good idea to do this page with our current stack with React and Firebase or whatever we end-up using as a DB. Pros/cons:
* :cat: first simple thing to release, would allow to go through the whole cycle and gather all pieces together
* :imp: can take a lot of time and effort (but it's not wasted effort, just delays lunch)

**Comment by Restuta** [comment]
![](http://media3.giphy.com/media/Zym9WJEXE0cBW/giphy.gif)

**Comment by Me4ta** [comment]
I think it's better to discuss it when we'll see we are almost ready. In this case our lunch will be predictable and we can measure how much time we have for creating this feature.

**Comment by Restuta** [comment]
@Me4ta but this has to be done before we "almost ready" we need a month or two for this page to be ON so we can gather meaningful amount of emails.

**Comment by Me4ta** [comment]
Then it's better to do it in simple way.

**Comment by Restuta** [comment]
I think this is not relevant anymore since calendar will be part of NCNCA now.
