### ISSUE TITLE
Duplicate keys on calendar page after clicking show/hide past events

### ISSUE THREAD

**Issue by graymur** [Restuta/rcn.io#297]
http://dl4.joxi.net/drive/2017/10/18/0004/2795/285419/19/2f2eac8998.jpg

**Comment by Restuta** [comment]
Which page? @graymur

**Comment by graymur** [comment]
@Restuta http://localhost:8888/calendars/usac-2017

**Comment by Restuta** [comment]
Got it, on it

**Comment by Restuta** [comment]
"never commit directly to master" and I failed that :|
