### ISSUE TITLE
Analyze feedback from Survey

### ISSUE THREAD

**Issue by Me4ta** [Restuta/rcn.io#30]
Survey (using https://www.surveygizmo.com/): 
>"Hi, ...,
We are building a product for racers like you and me, please take this VERY short (8 questions) survey, so we might be able to make your life a little bit easier.
http://sgiz.mobi/s3/Creating-Racing-calendar

>I found planning my racing season to be a painful process. I have to go to NCNCA calendar, open race flyers, look up places and estimate driving time, compare this with my usual calendar events like birthdays, etc. And after I am done I have to send this information somehow to my coach and share it with my team so we can all review and adjust… We think there should be a better way. But before we start, we need you help. Thanks in advance."

- [ ] ~~See if there is a difference how people in different categories do planning (take results table)~~
- [x] Create an ordered list of card data significance
- [x] Write down conclusions we made from the data
- [x] Move the report to the gitbook.com

[report_3534559.pdf](https://files.zenhub.io/5647acd3e5b473fe074af492)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by Restuta** [comment]
![](http://media0.giphy.com/media/TXBYwYvsQBUw8/giphy.gif)

**Comment by Me4ta** [comment]
[surveyReport.txt](https://files.zenhub.io/5647c2a5e5b473fe074af4d3)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by Me4ta** [comment]
#|points|criteria
-|------|---------
1| 341 |Type (RR, Crit, TT, etc) and amount of climbing
2| 245 |How far it away
3| 229 |If I liked it in the past
4| 197 |Number of teammates doing it
5| 186 |If I did it well in the past
6| 172 |Popularity/ Prestige/ Reputation of the event
7| 162 |What time does it start
8| 124 |Number of people registered

**Comment by Restuta** [comment]
@Me4ta could you please add description on what this table means and conclusions?

**Comment by Me4ta** [comment]
Cover letter:
"Hi, ...,
We are building a product for racers like you and me, please take this VERY short (up to 12 questions) survey, so we might be able to make your life a little bit easier.
https://me4ta18.typeform.com/to/WUX7Ns"

**Comment by Restuta** [comment]
how about:

"We are building a free product for racers like you and us, please help make it better  by answering just 12 VERY short questions, so we will make your life a little bit easier. 
(it takes 60-90 seconds to answer on avg)
Link to survey: http://j.mp/rcn-srv"

**Comment by Me4ta** [comment]
I would say:
- ... just up to 12 VERY short questions... (since we have two options and the second one is much shorter)
- ... it takes 2-3 minutes to answer...

**Comment by Restuta** [comment]
@Me4ta yes, but we don't have to be precise, if you insist we can do "12 or less" (but that is confusing "what does less mean"?)

agree with 2-3 minutes

**Comment by Restuta** [comment]
updated

**Comment by Me4ta** [comment]
Why you don't like "up to"? It might be confusing if someone will finish it in 6 questions...

**Comment by Restuta** [comment]
@Me4ta  6 or 12?

**Comment by Me4ta** [comment]
we have a short flow with 6 questions and the long one - with 12. So "up to 12" cover both ways, don't you think?

**Comment by Restuta** [comment]
+

**Comment by Me4ta** [comment]
Moved the report to the (gitbook.com/zocateamsurveyreview)[https://www.gitbook.com/book/me4ta/zocateamsurveyreview/details]

**Comment by Restuta** [comment]
Ok

**Comment by Restuta** [comment]
I would add dashes to name "zoca-team-survey-review"

**Comment by Me4ta** [comment]
I created the new one, for all our files:

[RCN wiki](https://www.gitbook.com/book/me4ta/rcn-wiki/details)

**Comment by Restuta** [comment]
great can you add me to collaborators/owners/admins (whatever it's called) I will map it to wiki.rcn.io
