### ISSUE TITLE
Re-launch survey in NCNCA groups

### ISSUE THREAD

**Issue by Restuta** [Restuta/rcn.io#31]
We can gather much more data which would give us better perspective.  We need to:

* [x] re-visit questions if we want to add/change anything (see the #30)
* [x] see if we can quickly recreate survey using http://www.typeform.com/, since survey gizmo is limited and $25 for options (and it wouldn't allow me to re-lunch current survey I don't see it)
* [x] add funny gif about bikes at the end with engaging message when we send survey, e.g. here is how Typeform made me pass their survey:

  >
  Take 2-Minute Survey
  Thanks for your time! 
  PS: There is a surprise waiting for you on the Thank You screen 🌟

  * [x] pick a message (we can do something like "There is a super-funny gif about our cats and bikes at the end.")
  * [x] take the gif
  * [x] update survey with it
* [x] ~~make sure "Do you use Github?" is in the survey step before last~~

#### Posting
* [x] post it on [NCNCA Most Competitive group](https://www.facebook.com/groups/NCNCA/) (facebook 1300+ members)
* [ ] [NCNCA FB Page](https://www.facebook.com/NorthernCaliforniaNevadaCyclingAssociation/?fref=ts) - asl for permission first
* [x] post on [NCNCA Women FB Group]( https://www.facebook.com/NCNCA-Women-1451747788373386/?fref=ts)
* [x] post on [NCNCA Yahoo Group](https://groups.yahoo.com/neo/groups/NCNCA/info)
* [x] post on [USA Cycling FB Group](https://www.facebook.com/groups/26253386690/)
* [x] post survey in SJBC Mailing list (on different day and time)
* [x] post survey in SJBC Facebook groups (also different day and time)
  * [x] [SJBC Race team group](https://www.facebook.com/groups/1692151247683443/1711029032462331)
 * [x] [SJBC Racing page](https://www.facebook.com/SJBCRacing/)

---
## Send this to people

(sorry if you've seen that already, didn't mean to annoy, ping me for coffee if annoyment is unbearable)

>We are building a free product for you, it'll help plan racing season faster. Please help to make it better by answering 12 VERY short questions, so we can focus on most needed features first.
(it takes 2-3 minutes to answer on avg. We measured :D + there is a bonus at the end!)

Link to survey: http://j.mp/rcn-srv

**Comment by Restuta** [comment]
![](http://media0.giphy.com/media/JlhMQR1RLL9u/giphy.gif)

**Comment by Me4ta** [comment]
Typeform with logical jump costs $20/month, but I'm working on this survey there. I'll let you know when it'll be ready

**Comment by Restuta** [comment]
@Me4ta added one todo =)

**Comment by Restuta** [comment]
@Me4ta we need extra question "Do you use Github?"

**Comment by Me4ta** [comment]
Funny gifs
http://giphy.com/gifs/lol-bike-raccoon-ynRy91kTW10Iw
http://giphy.com/gifs/bike-bicycle-dog-Z3L2dc4G83mmI
there is even long video about this kiddo :)
http://giphy.com/gifs/boy-bike-vYZSR0NdQXNpC 
http://giphy.com/gifs/bike-black-and-white-girls-d1vaWA1lsbIdy
http://giphy.com/gifs/bike-win-gorilla-GYSMIs7kJzGCI
http://giphy.com/gifs/bike-bicycle-monkey-yEU4aLQUU905i
http://giphy.com/gifs/art-life-rubber-x74hRB3dlYy9W
http://giphy.com/gifs/bike-album-kraftwerk-BIOcjkJQZ2hC8
http://giphy.com/gifs/ball-bike-oWwh3BkVbumeA
http://giphy.com/gifs/like-hero-jerk-WvZAvdTjIESfC

just in case
https://www.youtube.com/watch?v=Le4vGJ4U7AM

**Comment by Restuta** [comment]
I like this girl, but not sure it's a good use for the end.
![](https://media.giphy.com/media/d1vaWA1lsbIdy/giphy.gif)
also like these:
![](https://media.giphy.com/media/oWwh3BkVbumeA/giphy.gif)
![](https://media.giphy.com/media/aGF5UfFumPOec/giphy.gif)
