### ISSUE TITLE
Evaluate http://gitbook.com|gitbook.com :octocat: !

### ISSUE THREAD

**Issue by Restuta** [Restuta/rcn.io#38]
We need to evaluate gitbook.com for use as our documenation/data analysis results platform. Basic use is a replacement of wiki, but more collaborative. (comments and stuff)

Definition of done is decision of whether we should use it or not.

**Comment by Restuta** [comment]
![](http://media4.giphy.com/media/qZZ517aFZiV8c/giphy.gif)

**Comment by Me4ta** [comment]
It's already done. Here it is – [RCN wiki](https://me4ta.gitbooks.io/rcn-wiki/content), so I think, we can close this issue.

**Comment by Restuta** [comment]
great
