### ISSUE TITLE
Analyze Typeform Survey results

### ISSUE THREAD

**Issue by Restuta** [Restuta/rcn.io#49]
This is similar to #30 

 * [x] Create an ordered list of card data significance
 * [x] Write down conclusions we made from the data (in same format as in #30)
 * [x] Compare results to #30 and describe conclusions of this comparison
 * [x] Unsubscribe from Typeform payed plan
 * [x] See if there is a difference how people in different categories do planning (take results table)

**Comment by Restuta** [comment]
![](http://media1.giphy.com/media/2fS4EBf5Mlo6Q/giphy.gif)

**Comment by Me4ta** [comment]
What do you mean by that "Create an ordered list of card data significance"?

**Comment by Me4ta** [comment]
[surveyReportTypeform.md](https://files.zenhub.io/56b14a570617358f038b7494)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by Restuta** [comment]
@Me4ta I meant that we have a data what we show on Event Card, in order to understand what data is most useful for planning the season we need to understand the significance, e.g. what is most important for a racer (we ask this in that long question we discussed with you). So it's just ordered list of things that are important.

**Comment by Me4ta** [comment]
Criteria you use to decide on your events:

number | points | criteria
-----------|------|---------
1| 784 |Type (RR, Crit, TT, etc) and amount of climbing
2| 726 |If I liked it in the past
3| 655 |How far it away
4| 496 |Popularity/ Prestige/ Reputation of the event
5| 494 |Number of teammates doing it
6| 446 |What time does it start
7| 409 |Number of people registered

**Comment by Me4ta** [comment]
[Conclusions](https://me4ta.gitbooks.io/rcn-wiki/content/comparing-zoca-and-ncnca-results.html) from both surveys

**Comment by Restuta** [comment]
added task

**Comment by Me4ta** [comment]
[Wiki Survey results by category](http://wiki.rcn.io/survey/ncnca-survey-results-by-category.html)

**Comment by Restuta** [comment]
great, thanks

**Comment by Restuta** [comment]
It's hard to understand this table http://wiki.rcn.io/survey/ncnca-survey-results-by-category.html#criteria-you-use-to-decide-on-your-events compared to other ones, it's not clear what number in each column represents

**Comment by Me4ta** [comment]
I'll think how to change it
