### ISSUE TITLE
Create URL structure for Calendar

### ISSUE THREAD

**Issue by Me4ta** [Restuta/rcn.io#66]
We need to think this through, since we want our URL structure to be adequate from the beginning, current requirements are:
- calendar name should be part of the url
- url should be short
- should state be part of url? (I think only if we need to have similarly named calendars for different states like `rcn.io/cal/ca/racing` and `rcn.io/cal/ny/racing`

Possible options:
`rcn.io/cal/ncnca/2016` — name-centric, year is secondary
`rcn.io/cal/2016/ncnca` — year centric
`rcn.io/cals/ncnca/2016` — same as above but "cal" is in plural 

Current shema:
`rcn.io/calendars/{id}` (where id starts from `cal-` but we strip out `cal-`to make url better looking)

`rcn.io/calendars/ncnca-216`

**Comment by Restuta** [comment]
![](http://media3.giphy.com/media/vO6YcW2mRshTW/giphy.gif)

**Comment by Restuta** [comment]
So far we are using: 

`http://rcn.io/calendars/norcal-mtb`

so it's `calendars/{:id}/`

for events it can be:

`calendars/ncnca-2016/events/evt-afw23`
