### ISSUE TITLE
Set up server-side rendering

### ISSUE THREAD

**Issue by Me4ta** [Restuta/rcn.io#69]
Make sure our calendar and other pages are able to render with JavaScript disabled. Measure rendering time on prod using chrome's timeline. 

That would require Express setup and production server setup similar to what we have for development:
 - [x] Universal Redux
 - [x] Make sure we workaround dependency on a browser's container size 
  - [x] we can use `100%` width for initial render and then change it to a precise one, so cards would re-render after initial render, I guess that is fine

--
- [x]  _create tasks for this feature_

**Comment by Restuta** [comment]
![](http://media4.giphy.com/media/QOXwG4jMRGJTW/giphy.gif)
