### ISSUE TITLE
Too long event names are covered with location.

### ISSUE THREAD

**Issue by Me4ta** [Restuta/rcn.io#86]
We need to put (...) in long event names (as we do for location), since they are covered with location point.

**Comment by Restuta** [comment]
![](http://media2.giphy.com/media/mBK3T1nZAP1jq/giphy.gif)

**Comment by Restuta** [comment]
This is relevant only for narrow screens like iPhone 6 portrait (when card size is uncommon), I fixed it for the rest.

**Comment by Restuta** [comment]
so closing for now as no longer relevant
