### ISSUE TITLE
Support Events that are MOVED to a different date

### ISSUE THREAD

**Issue by Me4ta** [Restuta/rcn.io#87]
If event was moved to the different date we should:
- [x] mark it as "MOVED"
- [x] shade it
- [x] by clicking on old event scroll the calendar to the new date 

related #119

**Comment by Restuta** [comment]
![](http://media2.giphy.com/media/3phxgVFzVDTe8/giphy.gif)

**Comment by Restuta** [comment]
This is done, example https://rcn.io/events/evt-ncnca-2017-berkeley-hills-road-race-rJNQkkgF9Qx
