### ISSUE TITLE
Create basic Event Card UI

### ISSUE THREAD

**Issue by Restuta** [Restuta/rcn.io#9]
- [x] sketch of the card (post link to inVision)
- [x] React component
- [x] create variations and post them here (and inVision)
 - [x] use box-shadow to put emphasis on a card (e.g. google's material design)

Card should display following data: 
```
  "id": "evt-39101852",
    "discipline": "Road",
    "type": "Criterium",
    "name": "Cal Aggie Criterium",
    "date": "January 31st 2015",
    "distanceMi": 52,
    "durationMin": 64,
    "elevationGainFt": 1335,
    "startTime": "12:00 PM",
    "promoter": "Cal Aggie Cycling",
    "permit": "2016-3171",
    "location": {
      "streetAddress": "544 Castro Street",
      "city": "Salinas",
      "state": "CA",
      "zip": "91179"
    },
    "distanceToEventMi": 117,
    "estimatedTravelTime": "1h",
    "flyerUrl": "http://www.ncnca.org/sites/default/files/01/01/2014%20-%202%3A29am/183%20San%20Bruno%20Mountain%20Hill%20Climb%20OKED%203.pdf",
    "registrationUrl": "https://www.usacycling.org/register/2014-183"
  }
```

Also **add link to Results For past Events**

see [more](https://github.com/Restuta/rcn.io/blob/b3f185c1e834caba4ae5f8dac579979863036867/code/data/fake-events-generator/generated/2015-road.json)

--

### Importance of Event Attributes (based on survey #49)

number | points | criteria
-----------|------|---------
1| 784 |Type (RR, Crit, TT, etc) and amount of climbing
2| 726 |If I liked it in the past
3| 655 |How far it away
4| 496 |Popularity/ Prestige/ Reputation of the event
5| 494 |Number of teammates doing it
6| 446 |What time does it start
7| 409 |Number of people registered
--
_umbrella #3_

**Comment by Restuta** [comment]
One of the UI ideas I saw on [Parse blog](http://blog.parse.com/categories/events/):

<img width="689" alt="event-card" src="https://cloud.githubusercontent.com/assets/377261/10991244/a4951012-8410-11e5-92aa-8073e06456a0.png">

**Comment by Restuta** [comment]
We can design a card builder to experiment and prototype and take inspiration from TargetProcess:

![target-process](https://cloud.githubusercontent.com/assets/377261/11384772/a763717e-92c7-11e5-9116-923df2b24901.png)

This was our first attempt to design a card:
<img width="948" alt="2015-11-24_1625" src="https://cloud.githubusercontent.com/assets/377261/11384817/0b733604-92c8-11e5-865b-f399cab547df.png">

**Comment by Restuta** [comment]
Another example:

<img width="863" alt="2016-01-27_2108" src="https://cloud.githubusercontent.com/assets/377261/12635616/224d3cf4-c53a-11e5-9f6c-97752b72150b.png">

**Comment by Restuta** [comment]
One more

![rpix](https://cloud.githubusercontent.com/assets/377261/12635675/bc50a138-c53a-11e5-99ce-bb0e01a03815.png)

**Comment by Restuta** [comment]
![zoom](https://cloud.githubusercontent.com/assets/377261/12635982/d40c5c42-c53d-11e5-9a50-8c9f877110db.png)

**Comment by Me4ta** [comment]
As I understand it's a mobile design, but I think we can use it for sure, some of this features: Folding card and expanding fields. And I think we can shadow the background when user is working with card.

**Comment by Restuta** [comment]
our mocks https://projects.invisionapp.com/d/main#/console/1638951/134186710/preview
